routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/dashboard/{id}', 'HomeController@dashboard');

Route::group(['middleware' => 'auth', 'prefix'=> 'admin'], function () {
    Route::resource('dashboard', 'DashboardController');


    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

app/Dashboard.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
      'title', 'description', 
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
      'id',
  ];

   public function tiles(){
      return $this->belongsToMany('App\Tile');
    }
}

app/Tile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tile extends Model
{
  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
      'title', 'link', 'description', 'icon_class', 'color_class',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
      'id',
  ];

    public function tiles(){
      return $this->belongsToMany('App\Dashboard');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Dashboard;


const PAGINATION_LEVEL = 20;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dashboards = Dashboard::paginate(PAGINATION_LEVEL);
        return view('dashboards',['dashboards' => $dashboards]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.addFormDashboard');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'title' => 'required|max:255',
     ]);

     \DB::table('dashboards')->insert([
       ['title' => $request->input('title'), 'description' => $request->input('description'), 'public'=>$request->input('public')]
     ]);

     return redirect('admin/dashboard');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dashboard = Dashboard::findOrFail($id);
        return view('dashboard.showDashboard', ['dashboard'=> $dashboard]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dashboard = Dashboard::findOrFail($id);
        return view('dashboard.addFormDashboard', ['dashboard'=>$dashboard]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'title' => 'required|max:255',
     ]);

        $dashboard = Dashboard::findOrFail($id);
        $dashboard->title = $request->input('title');
        $dashboard->description = $request->input('description');
        $dashboard->public = $request->input('public');
        $dashboard->save();

        return redirect('admin/dashboard');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dashboard = Dashboard::findOrFail($id);
        $dashboard->delete();

        return redirect('admin/dashboard');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Tile;

class HomeController extends Controller
{
  public function index()
  {
      $tiles = Tile::all();
      return view('home', ['tiles'=>$tiles]);
  }
}

resources/views/dashboard/addFormDashboard.blade.php
@extends('vendor.adminlte.layouts.app')

@section('htmlheader_title')
	{{ trans('ui.dashboard') }}
@endsection


@section('main-content')
  <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title">{{trans('ui.dashboardForm')}}</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <form class="form-horizontal" method="POST" action={{ isset($dashboard) ? route('dashboard.update',['id'=>$dashboard->id]) : route('dashboard.store')  }}>
                <div class="box-body">
                  @isset($dashboard->id)
                    {{method_field('PATCH') }}
                    <input id="id" name="id" type="hidden" value={{$dashboard->id}}>
                  @endisset
                  {{ csrf_field() }}

                  <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">{{trans('ui.title')}}</label>

                    <div class="col-sm-10">
                      <input class="form-control" label={{trans('ui.title')}} type="text" name="title" value="{{ $dashboard->title or old('title') }}"></input>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">{{trans('ui.description')}}</label>

                    <div class="col-sm-10">
                      <textarea style="resize:none" name="description" class="form-control" rows="3" placeholder="" label={{trans('ui.description')}}>{{ $dashboard->description or old('description') }}</textarea>
                    </div>
                  </div>

                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                  <button type="submit" class="btn btn-primary pull-right">{{trans('ui.submit') }}</button>
                </div>
                <!-- /.box-footer -->
              </form>
            </div>
@endsection

resources/views/dashboard/showDashboard.blade.php
@extends('vendor.adminlte.layouts.app')

@section('htmlheader_title')
	{{ trans('ui.dashboard') }}
@endsection

@section('contentheader_title')
  {{$dashboard->title}}
@endsection
@section('contentheader_description')
  {{$dashboard->description}}
@endsection

@section('main-content')
	<example></example>
  <div class="box box-info">
              <div class="box-header with-border">
                <h3 class="box-title">{{trans('ui.assignedTiles')}}</h3>
              </div>
              <!-- /.box-header -->
                <div class="box-body">
                  @foreach ($dashboard->tiles as $tile)
                    <div class="col-lg-3 col-sm-6">
                            <div class="small-box {{$tile->color_class or 'bg-yellow'}} tile">
                                <div class="inner">
                                  <a href="{{$tile->link}}">
                                    <h3 class="relative">{{$tile->title}}</h3>
                                    <p>{{$tile->description}}</p>
            												@if($tile->icon_class)
                                    <div class="icon">
                                        <i class="{{$tile->icon_class}}"></i>
                                      </div>
            												@endif
                                    </a>
                                </div>
                                <a href="{{$tile->link}}" class="small-box-footer">Zobrazit <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                  @endforeach
                </div>
@endsection

resources/views/dashboards.blade.php
@extends('vendor.adminlte.layouts.app')

@section('htmlheader_title')
	{{ trans('ui.dashboard') }}
@endsection


@section('main-content')
	<div class="container-fluid spark-screen">
		<div class="row">

				<div class="col-lg-12">
		<div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">{{ trans('ui.dashboards') }}</h3>
							<div class="pull-right clearfix" >
								<a class='btn btn-default' href={{route('dashboard.create')}}>{{trans('ui.addNewDashboard')}}</a>
							</div>
            </div>

            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">

                <tbody>
									<tr>
	                  <th style="width: 10px">#</th>
	                  <th>{{ trans('ui.title') }}</th>
	                  <th>{{ trans('ui.description') }}</th>
										<th style="width: 40px">{{ trans('ui.show') }}</th>
										<th style="width: 40px">{{ trans('ui.edit') }}</th>
										<th style="width: 40px">{{ trans('ui.delete') }}</th>
	                </tr>
									@foreach ($dashboards as $dashboard)
										<tr>
		                  <td>{{$dashboard->id}}</td>
		                  <td>{{$dashboard->title}}</td>
		                  <td>{{$dashboard->description}}</td>
											<td><a class="btn btn-small btn-success" href="{{ route('dashboard.show', ['id' => $dashboard->id]) }}">{{ trans('ui.show') }}</a></td>
											<td><a class="btn btn-small btn-success" href="{{  route('dashboard.edit', ['id' => $dashboard->id]) }}">{{ trans('ui.edit') }}</a></td>
											<td>
												<form method="POST" action="{{ route('dashboard.destroy', ['id' => $dashboard->id])}}">
													{!! csrf_field() !!}
													<input type="hidden" name="_method" value="DELETE">
													<button class="btn btn-small btn-danger">{{ trans('ui.delete') }} </button>
												</form>
											</td>
										</tr>
									@endforeach
              </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                {{$dashboards->links()}}
              </ul>
            </div>
          </div>
				</div>
			</div>
		</div>

@endsection

resources/views/home.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	{{ trans('adminlte_lang::message.home') }}
@endsection


@section('main-content')
		<div class="row">
      @foreach ($tiles as $tile)
        <div class="col-lg-3 col-sm-6">
                <div class="small-box {{$tile->color_class or 'bg-yellow'}} tile">
                    <div class="inner">
                      <a href="{{$tile->link}}">
                        <h3 class="relative">{{$tile->title}}</h3>
                        <p>{{$tile->description}}</p>
												@if($tile->icon_class)
                        <div class="icon">
                            <i class="{{$tile->icon_class}}"></i>
                          </div>
												@endif
                        </a>
                    </div>
                    <a href="{{$tile->link}}" class="small-box-footer">Zobrazit <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
      @endforeach

 </div>
@endsection